{
 "title": "General Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "latency_interval", "query": "${VAR_LATENCY_INTERVAL}" }
  ]
 },
 "panels": [
  {
   "title": "Latency main routes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le,action) (rate(myapp_request_durations_histogram_seconds_bucket{action=\"all\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le,action) (rate(myapp_request_durations_histogram_seconds_bucket{action=~\"GET-api_token_check.*\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le,action) (rate(myapp_request_durations_histogram_seconds_bucket{action=~\"POST-app_users_infrastructure_adduseraction__invoke.*\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le,action) (rate(myapp_request_durations_histogram_seconds_bucket{action=~\"POST-app_api_report_create.*\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le,action) (rate(myapp_request_durations_histogram_seconds_bucket{action=~\"POST-app_api_report_change-status.*\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate (4**|5**)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "((sum(rate(myapp_http_5xx_responses_total[5m] )) by (action) or sum(rate(myapp_http_4xx_responses_total[5m])) by (action))/ sum(rate(myapp_request_durations_histogram_seconds_count[5m])) by (action) )*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate  by action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(myapp_http_requests_total{action=\"GET-api_token_check\"}[$__rate_interval])) by (action)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(myapp_http_requests_total{action=~\"all\"}[$__rate_interval])) by (action)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(myapp_http_requests_total{action=\"POST-app_users_infrastructure_adduseraction__invoke\"}[$__rate_interval])) by (action)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(myapp_http_requests_total{action=\"POST-app_api_report_create\"}[$__rate_interval])) by (action)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(myapp_http_requests_total{action=\"POST-app_api_report_change-status\"}[$__rate_interval])) by (action)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}